"""Relation 1-to-n added

Revision ID: a3b3e62f5281
Revises: 0b255c4b6915
Create Date: 2020-03-27 17:26:34.812370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b3e62f5281'
down_revision = '0b255c4b6915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('ct_range_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'languages', 'ct_ranges', ['ct_range_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.drop_column('languages', 'ct_range_id')
    # ### end Alembic commands ###
