"""Origin added

Revision ID: b43a908ae2c0
Revises: b9828ca988bc
Create Date: 2020-03-27 19:35:46.228122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43a908ae2c0'
down_revision = 'b9828ca988bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('origin', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'origin')
    # ### end Alembic commands ###
