"""n-to-n removed

Revision ID: b9828ca988bc
Revises: a3b3e62f5281
Create Date: 2020-03-27 17:39:06.529524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9828ca988bc'
down_revision = 'a3b3e62f5281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_categories',
    sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['ct_ranges.id'], name='language_categories_category_id_fkey'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name='language_categories_language_id_fkey')
    )
    # ### end Alembic commands ###
